// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-nboYRG0Hud_IyXWDOnJB5Ei7WAmEU5M',
    appId: '1:544703518580:web:edec031302b20f9b567e21',
    messagingSenderId: '544703518580',
    projectId: 'loginpage-612aa',
    authDomain: 'loginpage-612aa.firebaseapp.com',
    storageBucket: 'loginpage-612aa.appspot.com',
    measurementId: 'G-HPM489FV10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDniVYqSoWT2kGbugbmdCR9_aaWkyWr3QQ',
    appId: '1:544703518580:android:ea8b8a8a22510e78567e21',
    messagingSenderId: '544703518580',
    projectId: 'loginpage-612aa',
    storageBucket: 'loginpage-612aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxwUYPx2KmPmELqn6Jl6ojrveldBv0N3Q',
    appId: '1:544703518580:ios:11dc87aa1c774e1a567e21',
    messagingSenderId: '544703518580',
    projectId: 'loginpage-612aa',
    storageBucket: 'loginpage-612aa.appspot.com',
    iosBundleId: 'com.example.waythru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxwUYPx2KmPmELqn6Jl6ojrveldBv0N3Q',
    appId: '1:544703518580:ios:dc69a40470807147567e21',
    messagingSenderId: '544703518580',
    projectId: 'loginpage-612aa',
    storageBucket: 'loginpage-612aa.appspot.com',
    iosBundleId: 'com.example.waythru.RunnerTests',
  );
}
